pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - approved-reviews-by >= 1
    actions:
      merge:
        method: merge
      comment:
        message: 🤖 Automatic merge on pull request approval
